name: ecommerce_mobile_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_rating: ^2.0.2
  flutter_lucide: ^1.8.2
  flutter_intl_phone_field: ^0.0.7
  light_dark_theme_toggle: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/products/dress-1.png
    - assets/images/products/dress-2.png
    - assets/images/products/dress-3.png
    - assets/images/products/dress-4.png
    - assets/images/products/nike-2.png
    - assets/images/products/nike-3.png
    - assets/images/products/nike-4.png
    - assets/images/products/nike.png
    - assets/images/products/product_detail_one.png
    - assets/images/products/unsplash-1.jpg
    - assets/images/products/unsplash-2.jpg
    - assets/images/products/unsplash-3.jpg
    - assets/images/products/unsplash-4.jpg
    - assets/images/products/unsplash-5.jpg
    - assets/images/products/unsplash-6.jpg
    - assets/images/products/unsplash-7.jpg
    - assets/images/products/unsplash-8.jpg
    - assets/images/products/unsplash-9.jpg
    - assets/images/products/unsplash-10.jpg
    - assets/images/products/unsplash-11.jpg
    - assets/images/products/unsplash-12.jpg
    - assets/images/products/unsplash-13.jpg
    - assets/images/products/unsplash-14.jpg
    - assets/images/products/unsplash-15.jpg
    - assets/images/products/unsplash-16.jpg
    - assets/images/products/unsplash-17.jpg
    - assets/images/products/unsplash-18.jpg
    - assets/images/products/unsplash-19.jpg
    - assets/images/products/unsplash-20.jpg
    - assets/images/products/unsplash-21.jpg
    - assets/images/products/unsplash-22.jpg
    - assets/images/products/unsplash-23.jpg
    - assets/images/products/unsplash-24.jpg
    - assets/images/products/unsplash-25.jpg
    - assets/images/products/unsplash-26.jpg
    - assets/images/products/unsplash-27.jpg
    - assets/images/products/unsplash-28.jpg
    - assets/images/products/unsplash-29.jpg
    - assets/images/products/unsplash-30.jpg
    - assets/images/products/unsplash-31.jpg
    - assets/images/products/unsplash-34.jpg
    - assets/icons/facebook.png
    - assets/icons/google.png











    - assets/icons/shopping-cart.png
    - assets/icons/favourite.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Thin-Beta.otf
          weight: 100
        - asset: fonts/inter/Inter-ExtraLight-BETA.otf
          weight: 200
        - asset: fonts/inter/Inter-Light-BETA.otf
          weight: 300
        - asset: fonts/inter/Inter-Regular.otf
          weight: 400
        - asset: fonts/inter/Inter-Medium.otf
          weight: 500
        - asset: fonts/inter/Inter-SemiBold.otf
          weight: 600
        - asset: fonts/inter/Inter-Bold.otf
          weight: 700
        - asset: fonts/inter/Inter-ExtraBold.otf
          weight: 800       
        - asset: fonts/inter/Inter-Black.otf
          weight: 900

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
